# 2024-03-06 / LIPaS / (c) dmr-dj

title="makedepf90 / LIPaS configuration file"

[pkginfo]
name="makedepf90"
owner="Erik Edelmann"
license="GPL-2.0"
date=""
type="external"

[retrieve]
method="git"
path="https://github.com/dmr-dj/makedepf90.git"

[dependencies]
pkgs=""

[build]
lang="CC"
method="autotools"

[installtst]
exec="makedepf90"

# The End of All Things (op. cit.)
