# 2025-01-31 / LIPaS / (c) dmr-dj

title="uuid-fortran / LIPaS configuration file"

[pkginfo]
name="UUID-fortran"
owner="Jacob Williams"
license="BSD-3"
date=""
type="external"

[retrieve]
method="git"
path="https://github.com/jacobwilliams/uuid-fortran.git"

[dependencies]
pkgs=""

[build]
lang="FF"
method="make"
mkfile="ad-hoc"
modifier="internal|Makefile"
target="clean all library install"
location="src"

[installtst]
lib="libuuid-fortran"

# The End of All Things (op. cit.)
